version: "3"
services:
  mysql:
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "app"
  api:
    build:
      context: api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: dev
      DB_PASSWORD: password
      DB_NAME: app

  front:
    build:
      context: front
    ports:
      - "3000:3000"
